services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - ${DATA_DIR:-./data}:/app/data
      - ${METADATA_DIR:-./metadata}:/app/metadata

    environment:
      PYTHONUNBUFFERED: "1"
